---
- name: Instalação pacotes iniciais
  yum:
    name: "{{item}}"
    state: latest
  loop:
  - epel-release
  - python3
  - NetworkManager

- name: Enable Network Manager
  service: 
    name: NetworkManager
    enabled: true
    state: started

- name: Instalação de pacotes basicos
  yum:
    name: "{{pacotes_basic}}"
    state: latest

- name: Instalação de pacotes_dependencias_openshift 
  yum: 
    name: "{{pacotes_dependencias_openshift}}" 
    state: latest

- name: Clone a repo with separate git directory
  ansible.builtin.git:
    repo: https://github.com/openshift/openshift-ansible.git
    dest: /tmp/
    single_branch: yes
    branch: release-3.11 

- name: Instalação pip
  yum: 
    name: "{{item}}" 
    state: latest
  loop:
    - python3-pip.noarch
    - python2-pip.noarch

- name: Instalando o ANSIBLE 2.6
  pip:
    name: ansible==2.6

- name: Criando diretório do ANSIBLE
  file:
    path: /etc/ansible/
    state: directory
    owner: root
    mode: 0755

- name: Parando e removendo o FIREWALLD
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: true

- name: Iniciando DOCKER
  systemd:
    name: docker
    state: started
    enabled: yes
