 # Para definir a senha do usuário origin use o comando do openssl
 # $ openssl passwd -1 "senha"

---
- hosts: okd
  vars:
    master_node: okd01h
    user_senha:
    - { name: origin, senha: '$1$1oPayu.H$X9bjFPrN5V1zg4w5k6N8n0' }

  tasks:

    # cria usuário origin
    - name: Acionando usuarios
      user: name="{{item.name}}" password={{ item.senha }}
      with_items: "{{ user_senha }}"

    # copia padrão sudores 
    - name: Sudores config
      copy: 
        src: ./files/openshift.sudores
        dest: /etc/sudoers.d/openshift
        backup: yes
        owner: root
        mode: '0400'

    - name: Origin directory SSHKEY
      file:
        path: /home/origin/.ssh
        state: directory
        owner: origin
        mode: 0700

    # gera uma chave privada oara o usuário origin
    - name: Generate an OpenSSH keypair ECDSA
      openssh_keypair:
        path: /home/{{item.name}}/.ssh/id_rsa
        owner: "{{item.name}}"
        group: "{{item.name}}"
        type: ecdsa
        state: present
        mode: 0400
      with_items: "{{ user_senha }}"
      register: SSHKEY
      when: 
        - ansible_hostname == master_node

    # cria um arquivo com a chave publica
    - name: Pegar ecdsa-sha2-nistp256.pub                                                                               
      lineinfile:                                                                                              
        line: "{{item.public_key}}" 
        dest: ./files/ecdsa-sha2-nistp256.pub
        insertafter: EOF
      delegate_to: localhost                
      with_items: "{{ SSHKEY.results }}"
      when: 
        - ansible_hostname == master_node    

    #  copia a chave publica para os servidres do cluster openshift
    - name: Copiar ecdsa-sha2-nistp256.pub para os servidores
      authorized_key: user=origin key="{{ lookup('file', "./files/ecdsa-sha2-nistp256.pub") }}"     




