---
- hosts: okd
  vars:
    pacotes_basic:
    - epel-release 
    - yum-utils 
    - device-mapper-persistent-data 
    - lvm2 
    - nfs-utils 
    - git 
    - pyOpenSSL 
    - iptables-services
    - java
    - python-passlib
    - PyYAML
    - python-jinja2
    - python-paramiko
    - python-setuptools
    - python2-cryptography
    - sshpass
    - python-pip

    pacotes_dependencias_openshift:
    - docker 
    - centos-release-openshift-origin311      

    pacotes_openshift:
    - openshift-ansible
    
  tasks:

    - name: Atualização das maáquinas
      yum: 
        name: "*" 
        state: latest

    - name: Instalação de pacotes 
      yum: 
        name: "{{pacotes_basic}}" 
        state: latest

    - name: Instalação de pacotes_dependencias_openshift 
      yum: 
        name: "{{pacotes_dependencias_openshift}}" 
        state: latest

    - name: Instalação de pacotes do pacotes_openshift 
      yum: 
        name: "{{pacotes_openshift}}" 
        state: latest

    - name: Instalando o ANSIBLE 2.6
      pip:
        name: ansible==2.6

    - name: Criando diretório do ANSIBLE
      file:
        path: /etc/ansible/
        state: directory
        owner: root
        mode: 0755

    - name: Parando e removendo o FIREWALLD
      systemd:
        name: firewalld
        state: stopped
        enabled: no

    - name: Colocando regra de firewall para a porta 2222
      shell: iptables -I INPUT -p tcp --dport 2222 -j ACCEPT

    - name: Salvando regras de IPTABLES 
      shell: service iptables save

    - name: Reinicializando e ativando serviço do IPTABLES 
      systemd:
        name: iptables
        state: started
        enabled: yes


