- hosts: okd
  become: yes
  gather_facts: yes

  pre_tasks:
  - name: 'Atualizando repositorio'
    raw: 'yum -y update'

  roles:
  - { role: Install_OKD, tags: ["install_okd"]}

- hosts: hsproxys
  roles:
  - { role: Install_HAPROXY, tags: ["create_haproxy"]}
