SEUUSUARIO: seu_usuario

user_senha:
- { name: origin, 
    senha: '$1$1oPayu.H$X9bjFPrN5V1zg4w5k6N8n0' }

okd01: "12.0.20.61"
okd02: "12.0.26.84"
okd03: "12.0.23.61"
okd04: "12.0.29.26"
okd05: "12.0.20.174"

master_node: okd01

pacotes_basic:
  - device-mapper-persistent-data 
  - lvm2 
  - nfs-utils 
  - pyOpenSSL 
  - java
  - python-passlib
  - PyYAML
  - python-jinja2
  - python-paramiko
  - python-setuptools
  - python2-cryptography
  - sshpass
  - wget
  - git
  - net-tools
  - bind-utils
  - iptables-services
  - bridge-utils
  - bash-completion
  - kexec-tools
  - sos
  - psacct
  - yum-utils

pacotes_dependencias_openshift:
  - docker 
  - centos-release-openshift-origin311      

pacotes_openshift:
  - openshift-ansible











